* dicom.el - DICOM viewer - Digital Imaging and Communications in Medicine

#+html: <a href="https://www.gnu.org/software/emacs/"><img alt="GNU Emacs" src="https://github.com/minad/corfu/blob/screenshots/emacs.svg?raw=true"/></a>
#+html: <a href="https://elpa.gnu.org/packages/dicom.html"><img alt="GNU ELPA" src="https://elpa.gnu.org/packages/dicom.svg"/></a>
#+html: <a href="https://elpa.gnu.org/devel/dicom.html"><img alt="GNU-devel ELPA" src="https://elpa.gnu.org/devel/dicom.svg"/></a>
#+html: <a href="https://melpa.org/#/dicom"><img alt="MELPA" src="https://melpa.org/packages/dicom-badge.svg"/></a>
#+html: <a href="https://stable.melpa.org/#/dicom"><img alt="MELPA Stable" src="https://stable.melpa.org/packages/dicom-badge.svg"/></a>

DICOM stands for Digital Imaging and Communications in Medicine. DICOM files are
typically used for medical imaging with different modalities like US, CR, CT,
MRI or PET. This package adds the ability to view such files in Emacs. The
images and metadata are displayed in regular Emacs buffers. The package
registers itself in ~auto-mode-alist~ and ~magic-mode-alist~ for DICOMDIR directory
files and DICOM images (file extension *.dcm or *.ima). Furthermore the command
~dicom-open~ opens DICOMDIR directory files or DICOM image files interactively.

* Installation

Dicom.el is available from [[https://elpa.gnu.org/packages/dicom.html][GNU ELPA]]. You can install it directly via ~M-x package-install RET dicom RET~.
After installation, you can open ~DICOMDIR~ and DICOM image files.

The package relies on external programs from the dcmtk DICOM toolkit, which are
all widely available on Linux distributions.

- ~dcm2xml~ and ~dcmj2pnm~ from the dcmtk DICOM toolkit
- ~ffmpeg~ for video conversion (optional)
- ~mpv~ for video playing (optional)

* Supported files

The DICOM format is quite diverse. Since ~dcm2xml~ tool from the DICOM toolkit is
used to read the metadata, most uncorrupted DICOM files can be read. It can
still happen that the DICOM viewer is unable to display files nicely, if the
metadata records are not interpreted properly. Any help improving the package is
welcome.

* Contributions

Since this package is part of [[https://elpa.gnu.org/packages/dicom.html][GNU ELPA]] contributions require a copyright
assignment to the FSF.
